### ISSUE TITLE
Spanner appears on local build, but not on the heroku build. 

### ISSUE THREAD

**Issue by sohilpandya** [sohilpandya/Bidlt#137]

**Comment by sohilpandya** [comment]
this is what the console shows. 
![screen shot 2016-03-28 at 15 06 13](https://cloud.githubusercontent.com/assets/2305591/14079559/a2a88796-f4f6-11e5-8f39-f9bf9b834bef.png)

**Comment by katpas** [comment]
Done, but need to merge and check on heroku before closing issue

**Comment by sohilpandya** [comment]
Still an issue online. :disappointed: 

will look into it later.

**Comment by katpas** [comment]
Need to push changes to heroku to check
